/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Administrar_Componente;
import Modelo.Componente;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.print.DocFlavor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author pcbla
 */
public class AgregarComponente2 extends javax.swing.JFrame {

    /**
     * Creates new form IngresarComponente
     */
    public AgregarComponente2() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Seleccione un componente de cada tipo");
        cargarTablaFuselaje();
        cargarTablaAlas();
        cargarTablaEmpenaje();
        cargarTablaControlesFrenos();
        lblTrenAterrizaje.setText("Seleccione algun componente de la tabla Tren de Aterrizaje");
        lblTrenAterrizaje.setForeground(Color.red);
        lblEquipos.setText("Seleccione algun componente de la tabla Equipos");
        lblEquipos.setForeground(Color.red);
        lblCabina.setText("Seleccione algun componente de la tabla Cabina");
        lblCabina.setForeground(Color.red);
        lblMotor.setText("Seleccione algun componente de la tabla Motor");
        lblMotor.setForeground(Color.red);
        btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaMotor = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tablaTrenAterrizaje = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        tablaCabina = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTrenAterrizaje = new javax.swing.JLabel();
        lblEquipos = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblCabina = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Agregar componentes");

        jLabel2.setText("Tren de Aterrizaje");

        jLabel3.setText("Motor");

        tablaMotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMotorMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tablaMotor);

        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tablaEquipos);

        tablaTrenAterrizaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTrenAterrizaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTrenAterrizajeMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tablaTrenAterrizaje);

        tablaCabina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCabina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCabinaMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tablaCabina);

        jLabel4.setText("Equipos");

        jLabel5.setText("Cabina");

        jLabel6.setText("Componentes seleccionados");

        lblTrenAterrizaje.setText("jLabel7");

        lblEquipos.setText("jLabel8");

        lblMotor.setText("jLabel9");

        lblCabina.setText("jLabel10");

        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEquipos)
                                    .addComponent(lblTrenAterrizaje)
                                    .addComponent(lblMotor)
                                    .addComponent(lblCabina)))))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel2)
                        .addGap(534, 534, 534)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel3)
                        .addGap(438, 438, 438)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(999, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)
                        .addComponent(lblTrenAterrizaje)
                        .addGap(18, 18, 18)
                        .addComponent(lblEquipos)
                        .addGap(18, 18, 18)
                        .addComponent(lblMotor)
                        .addGap(18, 18, 18)
                        .addComponent(lblCabina)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        Administrar_Componente ac = new Administrar_Componente();
        int id_nave = ac.asociarAeronave();


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaTrenAterrizajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTrenAterrizajeMouseClicked
        // TODO add your handling code here:
        if (tablaTrenAterrizaje.getSelectedRow() >= 0) {
            lblTrenAterrizaje.setText("Componente Tren de Aterrizaje seleccionado");
            lblTrenAterrizaje.setForeground(Color.GREEN);
        }
        if (lblTrenAterrizaje.getForeground().equals(Color.GREEN) && lblEquipos.getForeground().equals(Color.GREEN) && lblCabina.getForeground().equals(Color.GREEN) && lblMotor.getForeground().equals(Color.GREEN)) {
            btnGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_tablaTrenAterrizajeMouseClicked

    private void tablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquiposMouseClicked
        // TODO add your handling code here:}
        if (tablaEquipos.getSelectedRow() >= 0) {
            lblMotor.setText("Componente Empenaje seleccionado");
            lblMotor.setForeground(Color.GREEN);
        }
        if (lblTrenAterrizaje.getForeground().equals(Color.GREEN) && lblEquipos.getForeground().equals(Color.GREEN) && lblCabina.getForeground().equals(Color.GREEN) && lblMotor.getForeground().equals(Color.GREEN)) {
            btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_tablaEquiposMouseClicked

    private void tablaMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMotorMouseClicked
        // TODO add your handling code here:

        if (tablaMotor.getSelectedRow() >= 0) {
            lblEquipos.setText("Componente Alas seleccionado");
            lblEquipos.setForeground(Color.GREEN);
        }
        if (lblTrenAterrizaje.getForeground().equals(Color.GREEN) && lblEquipos.getForeground().equals(Color.GREEN) && lblCabina.getForeground().equals(Color.GREEN) && lblMotor.getForeground().equals(Color.GREEN)) {
            btnGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_tablaMotorMouseClicked

    private void tablaCabinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCabinaMouseClicked
        // TODO add your handling code here:
        if (tablaCabina.getSelectedRow() >= 0) {
            lblCabina.setText("Componente Controles y Frenos seleccionado");
            lblCabina.setForeground(Color.GREEN);
        }
        if (lblTrenAterrizaje.getForeground().equals(Color.GREEN) && lblEquipos.getForeground().equals(Color.GREEN) && lblCabina.getForeground().equals(Color.GREEN) && lblMotor.getForeground().equals(Color.GREEN)) {
            btnGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_tablaCabinaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarComponente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarComponente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarComponente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarComponente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarComponente2().setVisible(true);
            }
        });
    }

    private void cargarTablaFuselaje() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaTrenAterrizaje.setModel(modelo);
        tablaTrenAterrizaje.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FABRICANTE");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        //.:Tamaño de columnas:.
        tablaTrenAterrizaje.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaTrenAterrizaje.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(140);
        columnModel.getColumn(2).setPreferredWidth(125);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(100);
        Administrar_Componente ac = new Administrar_Componente();
        ArrayList<Componente> listaFuselaje = ac.listarFiltro(1);
        Object[] fila = new Object[8];
        int num = listaFuselaje.size();
        for (int i = 0; i < num; i++) {
            fila[0] = listaFuselaje.get(i).getId();
            fila[1] = listaFuselaje.get(i).getDescripcion();
            fila[2] = listaFuselaje.get(i).getFabricante();
            fila[3] = listaFuselaje.get(i).getHoras_vuelo();
            fila[4] = listaFuselaje.get(i).getDias_vuelo();
            modelo.addRow(fila);
        }
        tablaTrenAterrizaje.updateUI();

    }

    private void cargarTablaAlas() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaMotor.setModel(modelo);
        tablaMotor.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FABRICANTE");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        //.:Tamaño de columnas:.
        tablaMotor.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaMotor.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(140);
        columnModel.getColumn(2).setPreferredWidth(125);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(100);
        Administrar_Componente ac = new Administrar_Componente();
        ArrayList<Componente> listaAlas = ac.listarFiltro(2);
        Object[] fila = new Object[8];
        int num = listaAlas.size();
        for (int i = 0; i < num; i++) {
            fila[0] = listaAlas.get(i).getId();
            fila[1] = listaAlas.get(i).getDescripcion();
            fila[2] = listaAlas.get(i).getFabricante();
            fila[3] = listaAlas.get(i).getHoras_vuelo();
            fila[4] = listaAlas.get(i).getDias_vuelo();
            modelo.addRow(fila);
        }
        tablaMotor.updateUI();

    }

    private void cargarTablaEmpenaje() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaEquipos.setModel(modelo);
        tablaEquipos.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FABRICANTE");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        //.:Tamaño de columnas:.
        tablaEquipos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaEquipos.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(140);
        columnModel.getColumn(2).setPreferredWidth(125);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(100);
        Administrar_Componente ac = new Administrar_Componente();
        ArrayList<Componente> listaEmpenaje = ac.listarFiltro(3);
        Object[] fila = new Object[8];
        int num = listaEmpenaje.size();
        for (int i = 0; i < num; i++) {
            fila[0] = listaEmpenaje.get(i).getId();
            fila[1] = listaEmpenaje.get(i).getDescripcion();
            fila[2] = listaEmpenaje.get(i).getFabricante();
            fila[3] = listaEmpenaje.get(i).getHoras_vuelo();
            fila[4] = listaEmpenaje.get(i).getDias_vuelo();
            modelo.addRow(fila);
        }
        tablaEquipos.updateUI();

    }

    private void cargarTablaControlesFrenos() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaCabina.setModel(modelo);
        tablaCabina.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FABRICANTE");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        //.:Tamaño de columnas:.
        tablaCabina.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaCabina.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(140);
        columnModel.getColumn(2).setPreferredWidth(125);
        columnModel.getColumn(3).setPreferredWidth(120);
        columnModel.getColumn(4).setPreferredWidth(100);
        Administrar_Componente ac = new Administrar_Componente();
        ArrayList<Componente> listaControlesFrenos = ac.listarFiltro(4);
        Object[] fila = new Object[8];
        int num = listaControlesFrenos.size();
        for (int i = 0; i < num; i++) {
            fila[0] = listaControlesFrenos.get(i).getId();
            fila[1] = listaControlesFrenos.get(i).getDescripcion();
            fila[2] = listaControlesFrenos.get(i).getFabricante();
            fila[3] = listaControlesFrenos.get(i).getHoras_vuelo();
            fila[4] = listaControlesFrenos.get(i).getDias_vuelo();
            modelo.addRow(fila);
        }
        tablaCabina.updateUI();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblCabina;
    private javax.swing.JLabel lblEquipos;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblTrenAterrizaje;
    private javax.swing.JTable tablaCabina;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTable tablaMotor;
    private javax.swing.JTable tablaTrenAterrizaje;
    // End of variables declaration//GEN-END:variables
}
