/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Administrar_Pilotos;
import Modelo.Piloto;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Celso
 */
public class IngresarPiloto extends javax.swing.JFrame {

    /**
     * Creates new form IngresarPiloto
     */
    class ComboItem {

            
         String key;
         String value;

        public ComboItem(String key, String value)
        {
            this.key = key;
            this.value = value;
        }

        @Override
        public String toString()
        {
            return key;
        }

        public String getKey()
        {
            return key;
        }

        public String getValue()
        {
            return value;
        }
    
}
 
    public IngresarPiloto() {
        initComponents();
        
        Administrar_Pilotos ap = new Administrar_Pilotos();
        try{
            ArrayList<Piloto> listaPiloto = ap.listarPilotoIngresar();
                for (int i = 0; i < listaPiloto.size(); i++) {
                this.cbRut.addItem(new ComboItem(listaPiloto.get(i).getRut()+" : "+listaPiloto.get(i).getNombre()+" "+listaPiloto.get(i).getApellidos(),String.valueOf(listaPiloto.get(i).getId_persona())));
                }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No hay usuarios para agregar a pilotos");
        }
            btnIngresarLicencia.setEnabled(false);
            btnIngresarLicencia.setVisible(false);
            btnIngresar.setEnabled(true);
            btnIngresar.setVisible(true);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jTextFieldDias = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        JDateMedicina = new com.toedter.calendar.JDateChooser();
        JDateUltimoVuelo = new com.toedter.calendar.JDateChooser();
        cbRut = new javax.swing.JComboBox();
        btnIngresarLicencia = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Piloto");

        jLabel2.setText("Horas de vuelo");

        jLabel3.setText("Usuario");

        jLabel4.setText("Dias de vuelo");

        jLabel5.setText("Vencimiento medicina");

        jLabel6.setText("Ultimo vuelo realizado");

        jTextFieldHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHorasKeyTyped(evt);
            }
        });

        jTextFieldDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiasKeyTyped(evt);
            }
        });

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/agregar.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/cancelar.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        JDateMedicina.setDateFormatString("dd/MMMM/yyyy");
        JDateMedicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JDateMedicinaKeyTyped(evt);
            }
        });

        JDateUltimoVuelo.setDateFormatString("dd/MMMM/yyyy");

        cbRut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        btnIngresarLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/agregar.png"))); // NOI18N
        btnIngresarLicencia.setBorder(null);
        btnIngresarLicencia.setBorderPainted(false);
        btnIngresarLicencia.setContentAreaFilled(false);
        btnIngresarLicencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLicenciaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tiene Licencias");

        jRadioButton1.setText("Si");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDias)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JDateUltimoVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHoras)
                            .addComponent(JDateMedicina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarLicencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngresar)
                        .addGap(79, 79, 79)
                        .addComponent(btnCancelar)))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addComponent(JDateMedicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(JDateUltimoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIngresarLicencia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        try{
            //vali combo
            if (cbRut.getSelectedItem().equals("Seleccione")) {
                JOptionPane.showMessageDialog(null, "Seleccione un Usuario");
                return;
            }
            
            //vali campos vacios
            if (jTextFieldHoras.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese las horas del piloto");
                return;
            }
            if (jTextFieldDias.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese los dias del piloto");
                return;
            }
            //vali fecha
            String fecha_medicina = null;
            String fecha_ultimo_vuelo = null;
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            
            try{
                Date fecha = JDateMedicina.getDate();
                Date hoy = new Date();
                if (fecha.before(hoy)) {
                    JOptionPane.showMessageDialog(null, "La fecha del vencimiento de la medicina no puede ser antes a la de hoy");
                    return;
                }
                fecha_medicina = df.format(fecha);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha de la Medicina mal ingresada");
                return;
            }
            
            try{
                Date fecha_ultimo = JDateUltimoVuelo.getDate();
                Date hoy = new Date();
                if (fecha_ultimo.after(hoy)) {
                     JOptionPane.showMessageDialog(null, "La fecha delultimo vuelo realizado no puede ser mayor a la de hoy");
                    return;
                }
                fecha_ultimo_vuelo = df.format(fecha_ultimo);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha del ultimo vuelo mal ingresado");
                return;
            }
            //datos
            Object item2 = cbRut.getSelectedItem();
            int id_persona = Integer.parseInt(((ComboItem)item2).getValue());
            int id_piloto =0;
            float horas = Float.parseFloat(jTextFieldHoras.getText());
            int dias = Integer.parseInt(jTextFieldDias.getText());
            
            Administrar_Pilotos ap = new Administrar_Pilotos();
            
            // validacion piloto repetido
            if (ap.buscarPilotoR(id_persona)) {
                JOptionPane.showMessageDialog(null, "Piloto ya ingresado");
                return;
            }
            //ibgresar
            Piloto piloto = new Piloto(id_piloto, horas, dias, fecha_medicina, fecha_ultimo_vuelo, id_persona);
            ap.ingresarPiloto(piloto);
            
        }catch(Exception ex){
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        MenuPrincipalOperador menu = new MenuPrincipalOperador();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextFieldHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHorasKeyTyped
       if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.') {
            evt.consume();
        }
        if (evt.getKeyChar()=='.'&&jTextFieldHoras.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldHorasKeyTyped

    private void jTextFieldDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiasKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDiasKeyTyped

    private void JDateMedicinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDateMedicinaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JDateMedicinaKeyTyped

    private void btnIngresarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLicenciaActionPerformed
        // TODO add your handling code here:
        try{
            //vali combo
            if (cbRut.getSelectedItem().equals("Seleccione")) {
                JOptionPane.showMessageDialog(null, "Seleccione un Usuario");
                return;
            }
            
            //vali campos vacios
            if (jTextFieldHoras.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese las horas del piloto");
                return;
            }
            if (jTextFieldDias.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese los dias del piloto");
                return;
            }
            //vali fecha
            String fecha_medicina = null;
            String fecha_ultimo_vuelo = null;
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            
            try{
                Date fecha = JDateMedicina.getDate();
                Date hoy = new Date();
                if (fecha.before(hoy)) {
                    JOptionPane.showMessageDialog(null, "La fecha del vencimiento de la medicina no puede ser antes a la de hoy");
                    return;
                }
                fecha_medicina = df.format(fecha);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha de la Medicina mal ingresada");
                return;
            }
            
            try{
                Date fecha_ultimo = JDateUltimoVuelo.getDate();
                Date hoy = new Date();
                if (fecha_ultimo.after(hoy)) {
                     JOptionPane.showMessageDialog(null, "La fecha delultimo vuelo realizado no puede ser mayor a la de hoy");
                    return;
                }
                fecha_ultimo_vuelo = df.format(fecha_ultimo);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha del ultimo vuelo mal ingresado");
                return;
            }
            //datos
            Object item2 = cbRut.getSelectedItem();
            int id_persona = Integer.parseInt(((ComboItem)item2).getValue());
            int id_piloto =0;
            float horas = Float.parseFloat(jTextFieldHoras.getText());
            int dias = Integer.parseInt(jTextFieldDias.getText());
            
            Administrar_Pilotos ap = new Administrar_Pilotos();
            
            // validacion piloto repetido
            if (ap.buscarPilotoR(id_persona)) {
                JOptionPane.showMessageDialog(null, "Piloto ya ingresado");
                return;
            }
            //ibgresar
            Piloto piloto = new Piloto(id_piloto, horas, dias, fecha_medicina, fecha_ultimo_vuelo, id_persona);
            ap.ingresarPiloto(piloto);
            
            IngresarLicencia il = new IngresarLicencia(piloto);
            
        }catch(Exception ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnIngresarLicenciaActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            btnIngresarLicencia.setEnabled(true);
            btnIngresarLicencia.setVisible(true);
            btnIngresar.setEnabled(false);
            btnIngresar.setVisible(false);
        }else{
            btnIngresarLicencia.setEnabled(false);
            btnIngresarLicencia.setVisible(false);
            btnIngresar.setEnabled(true);
            btnIngresar.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPiloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateMedicina;
    private com.toedter.calendar.JDateChooser JDateUltimoVuelo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresarLicencia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldHoras;
    // End of variables declaration//GEN-END:variables
}
