/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.text.SimpleDateFormat;

import java.util.Date;
import Controlador.Administrar_Aeronave;

import Database.Conexion;
import Modelo.Aeronave;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jordans
 */
public class IngresarAeronave extends javax.swing.JFrame {

    /**
     * Creates new form IngresarAeronave
     */
    public IngresarAeronave() {
        initComponents();
 RestrictedTextField descripcionLimit = new RestrictedTextField(txtmatricula);
 descripcionLimit.setLimit(5);
 descripcionLimit.setOnlyText(true);
 RestrictedTextField descripcionNUMERO = new RestrictedTextField(txtdiasvuelo);
 descripcionNUMERO.setOnlyNums(true);
  RestrictedTextField descripcionNUMERO2 = new RestrictedTextField(txthorasvuelo);
 descripcionNUMERO2.setOnlyNums(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbltiponave = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblhorasvuelo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbldiasvuelo = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        cmbtiponave = new javax.swing.JComboBox<>();
        lblmatriculac = new javax.swing.JLabel();
        lblhorasvuelito = new javax.swing.JLabel();
        lbldiasvuelito = new javax.swing.JLabel();
        lblmatriculita = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        txtdiasvuelo = new javax.swing.JTextField();
        txthorasvuelo = new javax.swing.JTextField();
        JDateVencimiento = new com.toedter.calendar.JDateChooser();
        JDateVencimiento1 = new com.toedter.calendar.JDateChooser();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Ingresar Aeronave");

        lbltiponave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltiponave.setText("Tipo Aeronave");

        lblestado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblestado.setText("Estado");

        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No Disponible" }));
        cmbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestadoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha Aeronavegabilidad");

        lblhorasvuelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblhorasvuelo.setText("Horas de Vuelo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Fecha de Inspeccion Anual");

        lbldiasvuelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldiasvuelo.setText("Días de Vuelo");

        btningresar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btningresar.setText("Ingresar Aeronave");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        cmbtiponave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helicoptero", "Aeronave" }));
        cmbtiponave.setToolTipText("");
        cmbtiponave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtiponaveActionPerformed(evt);
            }
        });

        lblmatriculac.setText("*");

        lblhorasvuelito.setText("*");

        lbldiasvuelito.setText("*");

        lblmatriculita.setText("Ingrese Matricula");

        JDateVencimiento.setDateFormatString("dd/MMMM/yyyy");

        JDateVencimiento1.setDateFormatString("dd/MMMM/yyyy");

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnvolver)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(lbltiponave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbldiasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblhorasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblmatriculita))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbestado, 0, 200, Short.MAX_VALUE)
                                        .addComponent(cmbtiponave, 0, 200, Short.MAX_VALUE))
                                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmatriculac, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txthorasvuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(txtdiasvuelo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbldiasvuelito, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblhorasvuelito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(JDateVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JDateVencimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btningresar)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmatriculac)
                            .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltiponave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbtiponave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDateVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblmatriculita))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDateVencimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblhorasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhorasvuelito)
                            .addComponent(txtdiasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthorasvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiasvuelito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvolver)
                    .addComponent(btningresar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed


        Administrar_Aeronave ingresar = new Administrar_Aeronave();
        String id = "0";
        String matricula = txtmatricula.getText().toUpperCase();
        String horasvuelo = txthorasvuelo.getText();
        String diasvuelo = txtdiasvuelo.getText();
        String tiponave = "" + cmbtiponave.getSelectedItem();
        String estado = "" + cmbestado.getSelectedItem();
       
            String fecha_aeronavegabilidad = null;
            String fecha_inspeccion = null;
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            
            try{
                Date fecha = JDateVencimiento.getDate();
                fecha_aeronavegabilidad = df.format(fecha);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
                return;
            }
            try{
                Date fecha1 = JDateVencimiento1.getDate();
                fecha_inspeccion = df.format(fecha1);
            }catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
                return;
            }
        if (tiponave.equals("Helicoptero")) {
            tiponave = "1";

        } else {
            tiponave = "2";

        }
            if (txthorasvuelo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Se asigna automaticamente el valor cero horas de vuelo");
               horasvuelo="0";
              
            }
            if (txtdiasvuelo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Se asigna automaticamente el valor cero dias de vuelo");
                diasvuelo="0";
                
            }
        switch (estado) {
           
            case "Disponible":
                estado = "V";
                break;
            case "No Disponible":
                estado = "M";
                break;
        }

        
            Aeronave nueva = new Aeronave(id, matricula, tiponave, estado, fecha_aeronavegabilidad, fecha_inspeccion, horasvuelo, diasvuelo);

            if (ingresar.buscarAeronave(nueva.getMatricula())) {
                JOptionPane.showMessageDialog(null, "La matricula de la aeronave ya esta registrado, por favor ingrese otra");
                txtmatricula.requestFocus();

            } else {

                if (ingresar.ingresarAeronave(nueva)) {
                    JOptionPane.showMessageDialog(null, "Se ingreso correctamente");
                   
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "¿Desea ingresar los componentes de la aeronave ingresada?", "confirmacion", dialogButton);
            if(dialogResult == 0) {
                      
                // codigo para cerrar y abrir la ventana componentes
                AgregarComponente ventanaComponente = new AgregarComponente();
                ventanaComponente.matriculaNave = matricula;
                ventanaComponente.setVisible(true);
                this.dispose();
            } else {
              JOptionPane.showMessageDialog(null, "no se ingresaron componentes");
            }

                } else {
                    JOptionPane.showMessageDialog(null, "no se puedo ingresar");
                }

            }

        

//        // TODO add your handling code here:
    }//GEN-LAST:event_btningresarActionPerformed


    private void cmbtiponaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtiponaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtiponaveActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
 ListarAeronave menu = new ListarAeronave();
        menu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateVencimiento;
    private com.toedter.calendar.JDateChooser JDateVencimiento1;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmbtiponave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbldiasvuelito;
    private javax.swing.JLabel lbldiasvuelo;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblhorasvuelito;
    private javax.swing.JLabel lblhorasvuelo;
    private javax.swing.JLabel lblmatriculac;
    private javax.swing.JLabel lblmatriculita;
    private javax.swing.JLabel lbltiponave;
    private javax.swing.JTextField txtdiasvuelo;
    private javax.swing.JTextField txthorasvuelo;
    private javax.swing.JTextField txtmatricula;
    // End of variables declaration//GEN-END:variables
}
