/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Administrar_Aeronave;
import Modelo.Aeronave;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jordans
 */
public class IngresarMantenimiento2 extends javax.swing.JFrame {

    /**
     * Creates new form IngresarMantenimiento
     */
    public IngresarMantenimiento2() {
        initComponents();
        cargarTablaComponentes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComponentes = new javax.swing.JTable();
        btnModificarCompte = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtmante.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtmante.setText("Ingresar Mantenimientos");
        txtmante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tablaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComponentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaComponentes);

        btnModificarCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/avanzar.png"))); // NOI18N
        btnModificarCompte.setBorder(null);
        btnModificarCompte.setBorderPainted(false);
        btnModificarCompte.setContentAreaFilled(false);
        btnModificarCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCompteActionPerformed(evt);
            }
        });

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/regresar.png"))); // NOI18N
        btnvolver.setBorder(null);
        btnvolver.setBorderPainted(false);
        btnvolver.setContentAreaFilled(false);
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtmante)
                .addContainerGap(599, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(btnvolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarCompte)
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtmante, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvolver, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificarCompte, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComponentesMouseClicked
        // TODO add your handling code here:

       
        btnModificarCompte.setEnabled(true);

        // lblComponenteSeleccionado.setText("Componente seleccionado");
        //lblComponenteSeleccionado.setForeground(Color.green);
    }//GEN-LAST:event_tablaComponentesMouseClicked

    private void btnModificarCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCompteActionPerformed

        // TODO add your handling code here:

        int resp = JOptionPane.showConfirmDialog(null, "Desea ingresar el mantenimiento a la aeronave seleccionada?");
        if (JOptionPane.OK_OPTION == resp) {
            btnModificarCompte.setEnabled(false);
            btnModificarCompte.setText("en curso...");
            int idCompte = Integer.parseInt(tablaComponentes.getValueAt(tablaComponentes.getSelectedRow(), 0).toString());

            IngresarMantenimiento modCompte= new IngresarMantenimiento();
            modCompte.idCompteMod = idCompte;
            modCompte.setVisible(true);
            this.dispose();
        } else {
           txtmante.requestFocus();
        }
    }//GEN-LAST:event_btnModificarCompteActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        btnvolver.setEnabled(false);
        btnvolver.setText("en curso...");
        MenuPrincipalOperador menu = new MenuPrincipalOperador();
        menu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarTablaComponentes() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
       
        tablaComponentes.setModel(modelo);
        tablaComponentes.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("TIPO AERONAVE");
        modelo.addColumn("ESTADO");
        modelo.addColumn("FECHA DE AERONAVEGABILIDAD");
        modelo.addColumn("FECHA DE INSPECCION ANUAL");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        
       
        //.:Tamaño de columnas:.
        tablaComponentes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaComponentes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(210);
        columnModel.getColumn(5).setPreferredWidth(190);
        columnModel.getColumn(6).setPreferredWidth(140);
        columnModel.getColumn(7).setPreferredWidth(130);
        Administrar_Aeronave ac = new Administrar_Aeronave();
        ArrayList<Aeronave> listaComponente = ac.listarAeronave2();
        Object[] fila = new Object[8];
        int num = listaComponente.size();
        
         
        for (int i = 0; i < num; i++) {
            fila[0] = listaComponente.get(i).getId();
            fila[1] = listaComponente.get(i).getMatricula();
           
           
            fila[4] = listaComponente.get(i).getFecha_aeronavegavilidad();
        
            fila[5] = listaComponente.get(i).getFecha_ultima_inspeccion_anual();
            fila[6] = listaComponente.get(i).getHoras_vuelo();
            fila[7] = listaComponente.get(i).getDias_vuelo();
             if (listaComponente.get(i).getTiponave().matches("1")){
                  fila[2] = "Helicoptero";
             }else {
                     fila[2] = "Aeronave"  ;   
                          }
            if (listaComponente.get(i).getEstado().matches("V")){
                  fila[3] = "Disponible";
             }else {
                     fila[3] = "Requiere Mantencion"  ;   
                          }
            modelo.addRow(fila);
        }
        tablaComponentes.updateUI();

    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarMantenimiento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarMantenimiento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarMantenimiento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarMantenimiento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarMantenimiento2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarCompte;
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaComponentes;
    private javax.swing.JLabel txtmante;
    // End of variables declaration//GEN-END:variables
}
