/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Administrar_Licencia;
import Controlador.Administrar_Pilotos;
import Modelo.Licencia;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Celso
 */
public class ListarLicenciaPiloto extends javax.swing.JFrame {

    /**
     * Creates new form ListarLicenciaPiloto
     */
    private void Clear_Table(){
       for (int i = 0; i < jTable1.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
   }
    
     DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    
    public ListarLicenciaPiloto() {
        initComponents();
        
        jTable1.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("NUMERO");
        modelo.addColumn("TIPO DE LICENCIA");
        modelo.addColumn("FECHA VENCIMIENTO");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        modelo.addColumn("ID DEL PILOTO");
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(75);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(140);
        columnModel.getColumn(4).setPreferredWidth(110);
        columnModel.getColumn(5).setPreferredWidth(110);
        columnModel.getColumn(6).setPreferredWidth(100);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        jTable1.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ListarPiloto = new javax.swing.JButton();
        ListarTodo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextRut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listar Licencia de Pilotos");

        ListarPiloto.setText("Listar por Piloto");
        ListarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPilotoActionPerformed(evt);
            }
        });

        ListarTodo.setText("Listar Todo");
        ListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTodoActionPerformed(evt);
            }
        });

        jLabel2.setText("Rut del Piloto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListarPiloto)
                        .addGap(18, 18, 18)
                        .addComponent(ListarTodo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextRut)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListarTodo)
                            .addComponent(ListarPiloto)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPilotoActionPerformed
             Clear_Table();
             
             String rut = jTextRut.getText();
             
             try{
                    Administrar_Licencia al = new Administrar_Licencia();

                    ArrayList<Licencia>lista = al.listarLicencia2(rut);

                    Object[] fila = new Object[9];
                    int num = lista.size();
                    for (int i = 0; i < num; i++) {
                        fila[0] = lista.get(i).getId();
                        fila[1] = lista.get(i).getNumero();
                        fila[2] = lista.get(i).getDescripcion();
                        fila[3] = lista.get(i).getFecha_vencimiento();
                        fila[4] = lista.get(i).getHoras_vuelo();
                        fila[5] = lista.get(i).getDias_vuelo();
                        fila[6] = lista.get(i).getId_piloto();
                        modelo.addRow(fila);
            }
            jTable1.updateUI();
        }catch(Exception ex){
            System.out.println(ex);
        }
        

    }//GEN-LAST:event_ListarPilotoActionPerformed

    private void ListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTodoActionPerformed
        Clear_Table();
        try{
            Administrar_Licencia al = new Administrar_Licencia();

            ArrayList<Licencia>lista = al.listarLicencia();
            
            Object[] fila = new Object[9];
            int num = lista.size();
            for (int i = 0; i < num; i++) {
                fila[0] = lista.get(i).getId();
                fila[1] = lista.get(i).getNumero();
                fila[2] = lista.get(i).getDescripcion();
                fila[3] = lista.get(i).getFecha_vencimiento();
                fila[4] = lista.get(i).getHoras_vuelo();
                fila[5] = lista.get(i).getDias_vuelo();
                fila[6] = lista.get(i).getId_piloto();
                modelo.addRow(fila);
            }
            jTable1.updateUI();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_ListarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarLicenciaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarLicenciaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarLicenciaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarLicenciaPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarLicenciaPiloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ListarPiloto;
    public javax.swing.JButton ListarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextRut;
    // End of variables declaration//GEN-END:variables
}
