/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Administrar_Aeronave;
import Modelo.Aeronave;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Duoc
 */
public class ListarAeronave extends javax.swing.JFrame {

    /**
     * Creates new form ListarAeronave
     */
    public ListarAeronave() {
        initComponents();
         cargarTablaComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComponentes = new javax.swing.JTable();
        btnEliminarCompte = new javax.swing.JButton();
        btnModificarCompte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarAeronave = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComponentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaComponentes);

        btnEliminarCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/eliminar.png"))); // NOI18N
        btnEliminarCompte.setToolTipText("");
        btnEliminarCompte.setBorder(null);
        btnEliminarCompte.setBorderPainted(false);
        btnEliminarCompte.setContentAreaFilled(false);
        btnEliminarCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCompteActionPerformed(evt);
            }
        });

        btnModificarCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/editar.png"))); // NOI18N
        btnModificarCompte.setBorder(null);
        btnModificarCompte.setBorderPainted(false);
        btnModificarCompte.setContentAreaFilled(false);
        btnModificarCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCompteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Listar Aeronaves");

        btnAgregarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/agregar.png"))); // NOI18N
        btnAgregarAeronave.setBorder(null);
        btnAgregarAeronave.setBorderPainted(false);
        btnAgregarAeronave.setContentAreaFilled(false);
        btnAgregarAeronave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAeronaveActionPerformed(evt);
            }
        });

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/regresar.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarAeronave)
                        .addGap(41, 41, 41)
                        .addComponent(btnModificarCompte)
                        .addGap(32, 32, 32)
                        .addComponent(btnEliminarCompte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarCompte)
                    .addComponent(btnModificarCompte)
                    .addComponent(btnAgregarAeronave)
                    .addComponent(btnMenu))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComponentesMouseClicked
        // TODO add your handling code here:

        btnEliminarCompte.setEnabled(true);
        btnModificarCompte.setEnabled(true);

       // lblComponenteSeleccionado.setText("Componente seleccionado");
        //lblComponenteSeleccionado.setForeground(Color.green);
    }//GEN-LAST:event_tablaComponentesMouseClicked

    private void btnEliminarCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCompteActionPerformed
     int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar la aeronave seleccionada?");
        if (JOptionPane.OK_OPTION == resp) {
            Administrar_Aeronave admp = new Administrar_Aeronave();
           
            
            String id = tablaComponentes.getValueAt(tablaComponentes.getSelectedRow(), 0).toString();
          
           
            admp.eliminarAeronave(id);
           
            
            cargarTablaComponentes();
            
        } else {
            cargarTablaComponentes();
        }

    }//GEN-LAST:event_btnEliminarCompteActionPerformed

    private void btnModificarCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCompteActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Seguro que desea modificar la aeronave seleccionada?");
        if (JOptionPane.OK_OPTION == resp) {
            int idCompte = Integer.parseInt(tablaComponentes.getValueAt(tablaComponentes.getSelectedRow(), 0).toString());
            ModificarAeronave modCompte= new ModificarAeronave();
            modCompte.idCompteMod = idCompte;
            modCompte.setVisible(true);
            this.dispose();
        } else {
            cargarTablaComponentes();
        }
    }//GEN-LAST:event_btnModificarCompteActionPerformed

    private void btnAgregarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAeronaveActionPerformed
        // TODO add your handling code here:
        IngresarAeronave menu = new IngresarAeronave();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarAeronaveActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
         MenuPrincipalOperador menu = new MenuPrincipalOperador();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAeronave().setVisible(true);
            }
        });
        
        
    }
private void cargarTablaComponentes() {
        //Definición de nombres y tamaño de las columnas al iniciar la ventana.
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
       
        tablaComponentes.setModel(modelo);
        tablaComponentes.getTableHeader().setReorderingAllowed(false);
        //.:Nombres de columnas:.
        modelo.addColumn("ID");
        modelo.addColumn("MATRICULA");
        modelo.addColumn("TIPO AERONAVE");
        modelo.addColumn("ESTADO");
        modelo.addColumn("FECHA DE AERONAVEGABILIDAD");
        modelo.addColumn("FECHA DE INSPECCION ANUAL");
        modelo.addColumn("HORAS DE VUELO");
        modelo.addColumn("DIAS DE VUELO");
        
       
        //.:Tamaño de columnas:.
        tablaComponentes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tablaComponentes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(100);
        columnModel.getColumn(7).setPreferredWidth(100);
        Administrar_Aeronave ac = new Administrar_Aeronave();
        ArrayList<Aeronave> listaComponente = ac.listarAeronave();
        Object[] fila = new Object[8];
        int num = listaComponente.size();
        
         
        for (int i = 0; i < num; i++) {
            fila[0] = listaComponente.get(i).getId();
            fila[1] = listaComponente.get(i).getMatricula();
    
            fila[4] = listaComponente.get(i).getFecha_aeronavegavilidad();
        
            fila[5] = listaComponente.get(i).getFecha_ultima_inspeccion_anual();
            fila[6] = listaComponente.get(i).getHoras_vuelo();
             fila[7] = listaComponente.get(i).getDias_vuelo();
             if (listaComponente.get(i).getTiponave().matches("1")){
                  fila[2] = "Helicoptero";
             }else {
                     fila[2] = "Aeronave"  ;   
                          }
            if (listaComponente.get(i).getEstado().matches("V")){
                  fila[3] = "Disponible";
             }else {
                     fila[3] = "No Disponible"  ;   
                          }
            modelo.addRow(fila);
        }
        tablaComponentes.updateUI();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAeronave;
    private javax.swing.JButton btnEliminarCompte;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModificarCompte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaComponentes;
    // End of variables declaration//GEN-END:variables
}
