/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pcbla
 */
public class MenuConsultor extends javax.swing.JFrame {

    /**
     * Creates new form MenuConsultor
     */
    public MenuConsultor() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnListarPiloto = new javax.swing.JButton();
        btnListarMantenimientos = new javax.swing.JButton();
        btnListarAeronaves = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Menu CONSULTOR");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/salir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListarPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListarPiloto.png"))); // NOI18N
        btnListarPiloto.setBorder(null);
        btnListarPiloto.setBorderPainted(false);
        btnListarPiloto.setContentAreaFilled(false);
        btnListarPiloto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPilotoActionPerformed(evt);
            }
        });

        btnListarMantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listarMantenimientos.png"))); // NOI18N
        btnListarMantenimientos.setBorder(null);
        btnListarMantenimientos.setBorderPainted(false);
        btnListarMantenimientos.setContentAreaFilled(false);
        btnListarMantenimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarMantenimientosActionPerformed(evt);
            }
        });

        btnListarAeronaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/listarAeronaves.png"))); // NOI18N
        btnListarAeronaves.setBorder(null);
        btnListarAeronaves.setBorderPainted(false);
        btnListarAeronaves.setContentAreaFilled(false);
        btnListarAeronaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarAeronaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAeronavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnListarPiloto)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnListarAeronaves)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(btnListarMantenimientos)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(btnListarPiloto)
                .addGap(27, 27, 27)
                .addComponent(btnListarAeronaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(63, 63, 63))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(btnListarMantenimientos)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Inicio btn = new Inicio();
        btn.setLocationRelativeTo(null);
        btn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnListarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPilotoActionPerformed
        
        ListarLicenciPilotoConsultor ip = new ListarLicenciPilotoConsultor();
        ip.setLocationRelativeTo(null);
        ip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarPilotoActionPerformed

    private void btnListarMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarMantenimientosActionPerformed
        // TODO add your handling code here:
         GenerarPDF pdf = new GenerarPDF();
        pdf.setLocationRelativeTo(null);
        pdf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarMantenimientosActionPerformed

    private void btnListarAeronavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAeronavesActionPerformed
        // TODO add your handling code here:
        ListarAeronaveConsultor listarNaves = new ListarAeronaveConsultor();
        listarNaves.setLocationRelativeTo(null);
        listarNaves.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btnListarAeronavesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsultor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsultor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsultor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsultor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsultor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarAeronaves;
    private javax.swing.JButton btnListarMantenimientos;
    private javax.swing.JButton btnListarPiloto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
